name = "todomvc"
version = "0.1.0"
defaultTargets = ["TodoMVC", "Todo"]
testDriver = "TodoTests"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "v4.31.0"

[[require]]
name = "html"
git = "https://github.com/paulbutcher/lean-html"
rev = "v0.6.0"

[[require]]
name = "htmx"
git = "https://github.com/paulbutcher/lean-htmx"
rev = "v0.5.0"

[[require]]
name = "routing"
git = "https://github.com/paulbutcher/lean-routing"
rev = "v0.5.0"

[[require]]
name = "middleware"
git = "https://github.com/paulbutcher/lean-middleware"
rev = "v0.3.0"

[[lean_lib]]
name = "Todo"

[[lean_lib]]
name = "TodoTests"

[[lean_exe]]
name = "TodoMVC"
root = "Main"
