version = 0.1

[default.deploy.parameters]
stack_name = "todomvc"
resolve_s3 = true
s3_prefix = "todomvc"
resolve_image_repos = true
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[default.global.parameters]
region = "us-east-1"
